[project]
name = "django-template"
version = "0.1.0"
description = "Starter template for Django projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "django-ninja>=1.4.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "ruff>=0.11.9",
]
